### ISSUE TITLE
Windows installation?

### ISSUE THREAD

**Issue by FatBrownDog** [openkoda/openkoda#1]
Hi,
Do you have info for Windows installation?

**Comment by arekdrysch** [comment]
The easiest way to start Openkoda on Windows is to install Docker Engine for Windows.
Then download this [docker compose file](https://raw.githubusercontent.com/openkoda/openkoda/main/docker/docker-compose.yaml).

and start instance by running 
`docker compose up`

**Comment by FatBrownDog** [comment]
I've managed to get it working on Windows...

Congrats! This is an awesome project. 

I'm willing to spend time to write tutorials, how-to's and code free add-ons (MIT-licensed).
