### ISSUE TITLE
Docker doesn't work...

### ISSUE THREAD

**Issue by FatBrownDog** [openkoda/openkoda#6]
I tried your docker...

I think it's missing Postgresql inside the container.

Can you check?

**Comment by arekdrysch** [comment]
@FatBrownDog 
The Openkoda docker image does not contain PostgreSQL Server. To run Openkoda in Docker with Postgres, please use Docker compose, that starts separate PostgreSQL contrainer: https://github.com/openkoda/openkoda#docker-compose
